export const SET_SITES = "SET_SITES";
export const POST_SITE = "POST_SITE";
export const DELETE_SITE = "DELETE_SITE";

export const SET_MESSAGES = "SET_MESSAGES";
export const CLEAR_MESSAGES = "CLEAR_MESSAGES";

export const START_LOADING_POST = "START_LOADING_POST";
export const STOP_LOADING_POST = "STOP_LOADING_POST";
export const START_LOADING_SITES = "START_LOADING_SITES";
export const STOP_LOADING_SITES = "STOP_LOADING_SITES";
export const START_LOADING_DELETE = "START_LOADING_DELETE";
export const STOP_LOADING_DELETE = "STOP_LOADING_DELETE";
